name: Fullstack Lint Check

on:
  pull_request:
  push:
    branches:
      - main # default branch name of my project

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v2
        with:
          node-version: "18.9.1" # Node.js version

      - name: Navigate to Backend Directory and Install Dependencies
        run: |
          cd backend
          npm ci
          npm install --only=dev

      - name: Run ESLint on Backend Code
        run: |
          cd backend
          npm run lint

      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v2
        with:
          node-version: "18.9.1" # Node.js version

      - name: Navigate to frontend Directory and Install Dependencies
        run: |
          cd frontend
          npm ci
          npm install --only=dev

      - name: Run ESLint on Frontend Code
        run: |
          cd frontend
          npm run lint
